security:
    encoders:
        App\Entity\Admin:
            algorithm: auto
        App\Entity\Student:
            algorithm: auto

    providers:
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
        app_user_provider:
            entity:
                class: App\Entity\Student
                property: email
        all_users:
            chain:
                providers: ['app_admin_provider', 'app_user_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            provider: app_admin_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\PlatformAuthenticator
            logout:
                path:   app_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
        students:
            provider: app_user_provider
            anonymous: true
            guard:
                authenticators:
                    - App\Security\PlatformAuthenticator
            logout:
                path:   app_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 6048000 # 10 week in seconds
                path:     /

    access_control:
         - { path: ^/a, roles: ROLE_ADMIN }
         - { path: ^/s, roles: ROLE_STUDENT }
